spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

---
spring:
  sql:
    init:
      platform: postgresql

---
spring:
  mvc:
    view:
      prefix: resources/templates/