spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  sql:
    init:
      platform: postgresql

  mvc:
    view:
      prefix: resources/templates/

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true